import { createTypes } from 'reduxsauce';

export default createTypes(`
  REQUEST_SENT
  REQUEST_RECEIVED_SUCCESSFUL
  REQUEST_RECEIVED_ERROR

  YOU_BELONG_HERE?
  CHECK_ACTIVE_USER
  ACTIVE_USER_CONFIRMED
  BYE_BY
`);
